-- Supabase SQL Editor'a TEK SEFERDE yapıştırıp çalıştır.
create table if not exists public.site_content (
  id bigint primary key,
  content jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.access_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label text,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.site_content enable row level security;
alter table public.access_codes enable row level security;

-- Tarayıcıdan bu tabloları doğrudan okumayı/yazmayı kapatıyoruz.
revoke all on public.site_content from anon, authenticated;
revoke all on public.access_codes from anon, authenticated;

-- Tek kullanımlık kodu atomik şekilde tüketir.
create or replace function public.consume_access_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  r public.access_codes;
begin
  update public.access_codes
    set used_at = now()
    where code = upper(trim(p_code)) and used_at is null
    returning * into r;

  if not found then
    return jsonb_build_object('ok',false,'message','Kod geçersiz veya daha önce kullanılmış.');
  end if;

  return jsonb_build_object('ok',true);
end;
$$;

revoke execute on function public.consume_access_code(text) from public, anon, authenticated;
-- Netlify server function service key ile çağırdığı için execute yetkisini service_role'a ver.
grant execute on function public.consume_access_code(text) to service_role;

-- İlk içerik
insert into public.site_content(id,content)
values (1,'{
 "title":"MCTiers & PVPTiers",
 "subtitle":"Kitlere katılım sürecini daha pratik hale getiren topluluk projesi.",
 "intro":"Onlarca farklı kit, farklı kurallar ve uzun bekleme süreleri. Burada proje hakkında bilgiler, indirme seçenekleri ve güncel bağlantılar tek yerde.",
 "discord":"stsse",
 "heroImage":"",
 "downloads":[
   {"title":"🐍 Python Dosyası","desc":"Kaynak kodun tamamı • Kod incelemek / düzenlemek isteyenler","url":"#"},
   {"title":"📁 Build Dosyaları","desc":"Derlenmiş ara dosyalar • Kendi EXE''ni üretmek isteyenler","url":"#"},
   {"title":"💻 EXE Dosyası","desc":"Windows için hazır çalıştırılabilir • Direkt kullanmak isteyenler","url":"#"}
 ],
 "warnings":[
   ["Discord ToS riski","Otomasyon, self-bot veya kullanıcı hesabını programatik olarak kontrol eden araçlar Discord kurallarına aykırı olabilir. Hesap kısıtlaması veya ban riski bulunabilir."],
   ["Sunucu kuralları","MCTiers, PVPTiers ve benzeri sunucuların kendi kuralları vardır. Otomasyon ilgili sunucunun kurallarına aykırı olabilir."],
   ["Hesap güvenliği","Üçüncü taraf dosyaları yalnızca güvendiğin kaynaktan indir. Kaynağı doğrulamadan çalıştırma."],
   ["Eğitim amacı","Proje Python, otomasyon mantığı ve yazılım geliştirme pratiği amacıyla paylaşılmaktadır. Kullanırken ilgili kurallara ve yasalara uy."]
 ]
}'::jsonb)
on conflict(id) do nothing;

-- İstersen Supabase Storage'da 'site-media' adlı PUBLIC bucket'ı panelden oluşturup
-- görseller için URL kullanabilirsin. Bu sürümde admin içerik alanına görsel URL'si eklemek için
-- heroImage alanı hazırdır.
